name: Build Check

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install Dependencies
        run: |
          npm ci --prefix web
          npm ci --prefix functions

      - name: Lint
        if: success()
        run: |
          npm run lint --prefix web
          npm run lint --prefix functions

      - name: Build
        if: success()
        run: |
          npm run prebuild --prefix web
          npm run build.dev --prefix web

      - name: Test
        if: success()
        run: |
          npm run test.sonar --prefix web
          npm run pree2e --prefix web # FIXME workaround for Issue #3 (chromedriver 74 error)
          npm run e2e --prefix web