name: Development

on:
  push:
    branches:
      - master

jobs:
  build-web:
    name: Build Web Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci --prefix web

      - name: Build
        if: success()
        run: |
          npm run prebuild --prefix web
          npm run build.dev --prefix web

      - name: Archive Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: web/dist

      - name: Send Slack Notification On Failure
        if: failure()
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Build Web Application
          mention: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


  build-functions:
    name: Build Firebase Cloud Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci --prefix functions

      - name: Build
        if: success()
        run: |
          npm run build --prefix functions

      - name: Send Slack Notification On Failure
        if: failure()
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Build Firebase Cloud Functions
          mention: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


  test-web:
    name: Test Web Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci --prefix web

      - name: Test
        if: success()
        run: |
          npm run test.sonar --prefix web
          npm run e2e --prefix web

      - name: SonarCloud Scan
        if: success()
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Send Slack Notification On Failure
        if: failure()
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Test Web Application
          mention: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


  test-rules:
    name: Test Firestore Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci --prefix firebase-test

      - name: Install Firebase Tools
        if: success()
        run: npm install -g firebase-tools

      - name: Test
        if: success()
        run: npm run test --prefix firebase-test

      - name: Send Slack Notification On Failure
        if: failure()
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Test Firestore Rules
          mention: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


  lint-web:
    name: Lint Web Aplication
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci --prefix web

      - name: Lint
        if: success()
        run: npm run lint --prefix web

      - name: Send Slack Notification On Failure
        if: failure()
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Lint Web Aplication
          mention: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


  lint-functions:
    name: Lint Firebase Cloud Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci --prefix web

      - name: Lint
        if: success()
        run: npm run lint --prefix functions

      - name: Send Slack Notification On Failure
        if: failure()
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Lint Firebase Cloud Functionsn
          mention: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


  deploy:
    name: Deploy
    needs: [build-web, build-functions, test-web, test-rules, lint-web, lint-functions]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: web/dist

      - name: Install Dependencies
        run: npm ci --prefix functions

      - name: Deploy to Firebase
        if: success()
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Send Slack Notification
        if: always()
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Build & Deploy Development
          mention: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}