name: Production

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci --prefix web

      - name: Build
        if: success()
        run: |
          npm run prebuild --prefix web
          npm run build.dev --prefix web

      - name: Archive Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: web/dist


  deploy:
    name: Deploy
    needs: [build-web, build-functions, test-web, test-rules, lint-web, lint-functions]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: web/dist

      - name: Install Dependencies
        run: npm ci --prefix functions

      - name: Deploy to Firebase
        if: success()
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}